config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'authors'
  root to: 'blog/posts#index'
  get 'about' => 'blog/authors#about'
  get 'portfolios' => 'blog/authors#portfolio'

  namespace :authors do
    get '/' => 'posts#index'
    get 'profile' => 'profiles#edit'
    put 'profile/info' => 'profiles#update'
    resources :portfolios
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end

  scope module: 'blog' do
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authors.rb
module Authors
  def self.table_name_prefix
    'authors_'
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  user_id          :integer
#  published        :boolean          default(TRUE)
#  published_at     :datetime
#

class Post < ApplicationRecord
  acts_as_taggable

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user

  PER_PAGE = 5

  scope :most_recent, -> { order(id: :desc) }
  scope :order_published, -> { order(published: :desc) }
  scope :published, -> { where(published: true) }
  scope :recent_paginated, -> (page) { most_recent.includes(:user, :tags).paginate(:page => page, :per_page => PER_PAGE ) }
  scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }
  scope :not_in_id, ->(id) { where('posts.id != ?',  id.to_s) }

  scope :list_for, -> (page, tag) do
    recent_paginated(page).with_tag(tag)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    if published_at.present?
      "Published #{published_at.strftime('%-b %-d, %Y')}"
    else
      "Not published yet."
    end
  end

  def publish
    update(published: true, published_at: Time.now)
  end

  def unpublish
    update(published: false, published_at: nil)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :portfolios, dependent: :destroy
  accepts_nested_attributes_for :portfolios, :reject_if => :all_blank , allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_user!

  layout 'authors'
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_user.posts.order_published.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_user.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    # PUT publish
    def publish
      @post.publish
      redirect_to authors_posts_url, notice: 'Have published post.'
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url, notice: 'Upublished post.'
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_user.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_user.posts.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
      end
  end
end

app/controllers/authors/profiles_controller.rb
module Authors
  class ProfilesController < AuthorController
    before_action :set_profile, only: [:edit, :update]
    def edit
    end

    def update
      current_user.update_attributes(profile_params)
      redirect_to authors_profile_path
    end

    private
    #
    def set_profile
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:user).permit(:birthday, :summary, :phone, :skills => [:name, :percent], portfolios_attributes: [:id, :title, :image, :url, :use_skills, :summary, :_destroy] )
    end
  end
end

app/controllers/blog/authors_controller.rb
module Blog
  class AuthorsController < BlogController
    # GET /posts
    # GET /posts.json
    def about
      @author = User.last
    end
    
    def portfolio
      @portfolios = User.last.portfolios
    end
  end
end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController
    # GET /posts
    # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
      @tag = @post.tag_list
      @similars = Post.with_tag(@tag).not_in_id(@post.id)
    end

    private

    def storage
      Post.published
    end
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields btn btn-primary form-control", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/authors/profiles_helper.rb
module Authors::ProfilesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/authors/posts/_form.html.erb
<%= form_with(model: post, local: true, url: url) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-3">
      <div class="card">
        <div class="card-body">
          <% if @post.new_record? %>
          <h4 class="card-title"><b>New post</b></h4>
          <% else %>
          <h4 class="card-title">
            <b>Edit</b>
            <span><%= @post.title %></span>
          </h4>
          <% end %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="field">
              <%= form.label :title %>
              <%= form.text_field :title, id: :post_title %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= form.label :banner_image_url %>
              <%= form.text_field :banner_image_url, id: :post_banner_image_url %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= form.label :description %>
              <%= form.text_area :description, id: :post_description %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= form.label :tags, "Tags" %>
              <%= form.text_field :tag_list, id: :post_tags %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="actions">
              <%= form.submit "Save blog post", :class => "btn btn-block btn-primary" %>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-9">
      <div class="field">
        <%= form.trix_editor :body, :rows => 50 %>
      </div>
    </div>
  </div>

<% end %>

app/views/authors/posts/_post.html.erb
<tr>
  <td><%= link_to post.title, authors_post_path(post) %></td>
  <td><%= raw post.tags.map{ |t| link_to t.name, "#" }.join(', ') %></td>
  <td><%= post.description %></td>
  <% if post.published? %>
  <td><%= link_to 'unpublish', unpublish_authors_post_path(post), :method => :put, :remote => true, class: 'btn btn-sm btn-primary' %></td>
  <% else %>
  <td><%= link_to 'Publish', publish_authors_post_path(post), :method => :put, :remote => true, class: 'btn btn-sm btn-success' %></td>
  <% end %>
  <td><%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %></td>
  <td><%= link_to 'Remove', authors_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
</tr>

app/views/authors/posts/edit.html.erb
<%= render 'form', post: @post, url: authors_post_url(@post) %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', authors_posts_path %>

app/views/authors/posts/index.html.erb
<% unless notice.blank? %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Tags</th>
      <th>Body</th>
      <th>Description</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% unless @posts.empty? %>
  <tbody>
    <%= render @posts %>
  </tbody>
  <% end %>
</table>

<br>

<%= link_to 'New Post', new_authors_post_path, :class => 'btn btn-primary' %>

app/views/authors/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post, url: authors_posts_url %>

<%= link_to 'Back', authors_posts_path %>

app/views/authors/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<%= @post.display_day_published %>
<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @post.slug %>
</p>

<%= link_to 'Edit', edit_authors_post_path(@post) %> |
<%= link_to 'Back', authors_posts_path %>

app/views/authors/profiles/_portfolio_fields.html.erb
<fieldset class="card card-body">
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :image %>
      <%= f.text_field :image, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :url %>
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :use_skills %>
      <%= f.text_field :use_skills, :class => 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :summary %>
      <%= f.text_area :summary, :class => 'form-control' %>
    </div>
    <%= f.hidden_field :_destroy %>
    <%= link_to "Remove Portfolio", '#', class: "remove_fields" %>
</fieldset>

app/views/authors/profiles/edit.html.erb
<div class="card card-body">
  <%= form_for @user, url: authors_profile_info_path, method: :put do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :birthday %>
      <%= f.date_select :birthday, :class => 'form-control', :start_year => 1970, :end_year => 2000 %>
    </div>

    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :summary %>
      <%= f.trix_editor :summary, :row => 15, :class => 'form-control' %>
    </div>
    <h3><b>Skills</b></h3>
    <div class="field skills_field">
      <% unless @user.skills.blank? %>
        <% @user.skills.each do |x| %>
          <div class="fieldset">
            <div class="row no-gutters">
              <div class="column">
                <%= f.label :skill_name, 'Skill name' %>
                <%= f.text_field "skills[][name]", value: x['name'], id: :skill_name, :class => 'form-control' %>
              </div>
              <div class="column">
                <%= f.label :skills_percent, 'Skill percent' %>
                <%= f.number_field "skills[][percent]", value: x['percent'], id: :skills_percent, :class => 'form-control' %>
              </div>
            </div>
            <a href="#" class="remove_skill">Remove skill</a>
          </div>
        <% end %>
      <% else %>
        <div class="fieldset">
          <div class="row no-gutters">
            <div class="column">
              <%= f.label :skill_name, 'Skill name' %>
              <%= f.text_field "skills[][name]", value: nil, id: :skill_name %>
            </div>
            <div class="column">
              <%= f.label :skills_percent, 'Skill percent' %>
              <%= f.number_field "skills[][percent]", value: nil, id: :skills_percent %>
            </div>
            <a href="#" class="remove_skill">Remove skill</a>
          </div>
        </div>
      <% end %>
    </div>
    <a href="#" class="btn btn-primary form-control add_new_skill">Add new skill</a>
    <h3><b>Portfolio</b></h3>
    <%= f.fields_for :portfolios do |builder| %>
      <%= render 'portfolio_fields', :f => builder %>
    <% end %>
    <div>
      <%= link_to_add_fields "Add Portfolio", f, :portfolios %>
    </div>
    <div class="actions">
      <%= f.submit "Save", :class => 'btn btn-success form-control' %>
    </div>
  <% end %>
</div>

app/views/blog/authors/about.html.erb
<%= provide(:page_name, link_to('Home back', '/')) %>

<div class="col-md-12 blog-post">

  <!-- My Intro Start -->
  <div class="post-title margin-bottom-30">
    <h1>Hi, I am
      <span class="main-color"><%= @author.name %></span>
    </h1>
  </div>
  <!-- My Intro End -->

  <div class="summary">
    <%= @author.summary.html_safe %>
  </div>

  <!-- My Service Start -->
  <div class="post-title">
    <h1>My
      <span class="main-color">Skills</span>
    </h1>
  </div>

  <div class="list list-style-2 margin-top-30">
    <div class="row no-gutter">
      <% @author.skills.each do |x| %>
        <div class="col-3">
          <b><%= x['name'] %></b>
        </div>
        <div class="col-9">
          <div class="progress">
            <div class="progress-bar bg-info" role="progressbar" style="width: <%= x['percent'] %>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <div class="level">
            <ul>
              <li>Beginner</li>
              <li>Junior</li>
              <li>Middle</li>
              <li>Senior</li>
              <li>Master</li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <!-- My Service End -->

</div>

app/views/blog/authors/portfolio.html.erb
<%= provide(:page_name, 'My Portfolio') %>

<div class="col-md-12 blog-post">

  <!-- Intro Start -->
  <div class="post-title margin-bottom-30">
    <h1>Let's take a look on
      <span class="main-color">My Work</span>
    </h1>
  </div>
  <!-- Intro End -->

  <!-- Portfolio Start -->
  <div>
    <!-- Portfolio Detail Start -->
    <% @portfolios.each do |portfolio| %>
    <div class="row portfolio">
      <div class="col-12 custom-pad-2">
        <div class="table-responsive">
          <table class="table table-bordered">
            <tbody>

              <tr>
                <td>
                  <b>Project name</b>
                </td>
                <td><%= portfolio.title %></td>
              </tr>

              <tr>
                <td>
                  <b>Skills</b>
                </td>
                <td><%= portfolio.use_skills %></td>
              </tr>

              <tr>
                <td>
                  <b>Url</b>
                </td>
                <td>
                  <%= link_to portfolio.title, portfolio.url %>
                </td>
              </tr>

              <tr>
                <td>
                  <b>About Project</b>
                </td>
                <td><%= portfolio.summary %></td>
              </tr>
            </tbody>
          </table>

        </div>
      </div>
    </div>
    <% end %>
    <!-- Portfolio Detail End -->
  </div>
  <!-- Portfolio End -->
</div>

app/views/blog/posts/index.html.erb
<%= provide(:page_name, 'My Blog') %>

<div class="front-blog">
  <% @posts.each do |post| %>
  <div class="col-md-12 card">
    <div class="post-image">
      <%= link_to post_path(post) do %>
        <%= image_tag(post.banner_image_url, :alt => post.title, :class => 'card-img-top') unless post.banner_image_url.blank? %>
      <% end %>
    </div>
    <div class="card-body">
      <div class="post-title">
        <h1>
          <%= link_to post.title, post_path(post) %>
        </h1>
      </div>
      <div class="tags">
        <%= raw post.tags.map { |t| link_to t.name, posts_path(tag: t.name) }.join(', ') %>
      </div>
      <div class="post-info">
        <span><%= post.display_day_published %> / by
          <%= post.user.name %>
        </span>
      </div>
      <p class="card-text"><%= post.description %></p>
    </div>
  </div>
  <% end %>
  <div class="apple_pagination">
    <%= will_paginate @posts, :container => false %>
  </div>
</div>

app/views/blog/posts/show.html.erb
<%= provide(:page_name, link_to('Home back', '/')) %>

<div class="col-md-12 blog-post">

  <!-- Post Headline Start -->
  <div class="post-title">
    <h1><%= @post.title %></h1>
  </div>
  <div class="tags">
    <%= raw @post.tags.map { |t| link_to t.name, posts_path(tag: t.name) }.join(', ') %>
  </div>
  <!-- Post Headline End -->

  <!-- Post Detail Start -->
  <div class="post-info">
    <span><%= @post.display_day_published %> / by
      <%= link_to @post.user.name, about_path %>
    </span>
  </div>
  <!-- Post Detail End -->
  <div class="content">
    <%= @post.body.html_safe %>
  </div>

  <!-- You May Also Like Start -->
  <% unless @similars.empty?  %>
  <div class="you-may-also-like margin-top-50 margin-bottom-50">
    <h3>You may also like</h3>
    <div class="row">
      <% @similars.each do |s| %>
      <div class="col-md-4 col-sm-6 col-xs-12">
        <%= link_to post_path(s) do %>
          <p><%= s.title %></p>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>
  <!-- You May Also Like End -->
</div>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to 'My Blog', authors_path, :class => 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item active">
                <%= link_to('Web view', root_path, :class => 'nav-link', :target => 'blank') %>
            </li>
            <li class="nav-item">
                <%= link_to authors_profile_path, :class => 'nav-link' do %>
                  <b>Hello</b> <%= current_user.name %>
                <% end %>
            </li>
            <li class="nav-item">
              <u><%= link_to 'Logout', destroy_user_session_path, :method => :delete, :class => 'nav-link' %></u>
            </li>
          </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="content">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>img{max-width: 100%}</style>
  </head>

  <body>
    <div id="main">
      <div class="container">
        <div class="row">

          <!-- About Me (Left Sidebar) Start -->
          <div class="col-md-3">
            <div class="about">

              <div class="my-pic">
                <img src="https://lh3.googleusercontent.com/F2Sv6pUWgMqveFYLN0KzcZf8xJ3R8ChQti_7ul6taZBpahnIDazWyz-ei67xkt1eeTjcnaFYENt8_TIH0c-kpOxYS8bw6jB_JgTDQOGyGA2A24jITyspezT-eIGp3aCOXEToY4EdpC-LErYxuSdC4c19zD7-yg5II-uVMnmP97H0hzXxhundWImhkkob1IWrxOyi02nYw3BKRj5V-p2CL5zYHCSj3_Awzms3gRfcWLxrchKpSKx1hADNStZRU1h0hRQ-nK9ZmN1ko1_5MB83Q8qraJriwz-elw3INfdXAmX-MtUnTsi_uhrbdxzI_u-MrbFySc91nTXkYbGn6iJ85ZP1RdHAuJiEcr9BUjDybjvRTqnszw0kdwL-mI_pdwiUCJ2Q06R64UNhE5xbwtrhQ-DBmYTyHl4tT2ezZDvlYKzss8gZ09Qy-TyRrNK4Iw63At4LERPimqEl9KcQH8GUMvP5JTLmKgRvVqf_6Xpl395BdFJXrZak7Z6OEjon-NRKGHW2tu5DG3fLai54jpxHiWCaSQtgV-byw_wD5t54SdFZSnAR5JmokIqUo1Yksa2G_lvbvmnJxv3F-FNGE2CNKegW7hXbVGf8A4Rq333NJj620wpbLBWD0O0-DFOuOn-cFeecKhSzGNx1lghdsBo8NRw4Ry5cB0UHDQ=s653-no" alt="Nhat Pham">
                <a href="javascript:void(0)" class="collapsed" data-target="#menu" data-toggle="collapse">
                    <%= fa_icon "bars", :class => 'menu' %>
                </a>
                <div id="menu">
                  <ul class="menu-link">
                    <li>
                      <%= link_to 'Home', '/' %>
                    </li>
                    <li>
                      <%= link_to 'About', about_path %>
                    </li>
                    <li>
                      <%= link_to 'Portfolios', portfolios_path %>
                    </li>
                  </ul>
                </div>
              </div>

              <div class="my-detail">

                <div class="white-spacing">
                  <h1>Pham Van Nhat</h1>
                  <span>Web Developer</span>
                </div>

                <ul class="social-icon">
                  <li>
                    <%= link_to 'https://www.facebook.com/vannhat95.dsn', :class => 'facebook', :target => '_blank' do %>
                      <%= fa_icon "facebook" %>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to 'https://twitter.com/butrentron', :class => 'twitter', :target => '_blank' do %>
                      <%= fa_icon "twitter" %>
                    <% end %>
                  </li>
                  <li>
                    <a href="#" target="_blank" class="linkedin">
                        <%= fa_icon "linkedin" %>
                    </a>
                  </li>
                  <li>
                    <%= link_to 'https://github.com/nhatphamcdn', :class => 'github', :target => '_blank' do %>
                      <%= fa_icon "github" %>
                    <% end %>
                  </li>
                </ul>

              </div>
            </div>
          </div>
          <!-- About Me (Left Sidebar) End -->

          <!-- Blog Post (Right Sidebar) Start -->
          <div class="col-md-9">
            <div class="col-md-12 page-body">
              <div class="row">
                <div class="sub-title">
                  <h2><%= yield(:page_name) %></h2>
                  <a href="contact.html">
                    <i class="icon-envelope"></i>
                  </a>
                </div>
                <div class="col-md-12 content-page">
                  <%= yield %>
                </div>
              </div>

            </div>

            <!-- Footer Start -->
            <div class="col-md-12 page-body margin-top-50 footer">
              <footer>
                <ul class="menu-link">
                  <li>
                    <%= link_to 'Home', '/' %>
                  </li>
                  <li>
                    <%= link_to 'About', about_path %>
                  </li>
                  <li>
                    <%= link_to 'Portfolios', portfolios_path %>
                  </li>
                  <li>
                    <a href="http://pommmy.com/" target="_blank">Nhật Phạm</a>
                  </li>
                </ul>

                <p>© Copyright 2017 DevBlog. All rights reserved</p>

                <!-- UiPasta Credit Start -->
                <div class="uipasta-credit">Design By
                  <a href="http://www.uipasta.com" target="_blank">UiPasta</a>
                </div>
                <!-- UiPasta Credit End -->

              </footer>
            </div>
            <!-- Footer End -->

          </div>
          <!-- Blog Post (Right Sidebar) End -->

        </div>
      </div>
    </div>

    <!-- Back to Top Start -->
    <a href="#" class="scroll-to-top">
      <i class="fa fa-long-arrow-up"></i>
    </a>
    <!-- Back to Top End -->

  </body>
</html>